### ISSUE TITLE
Why didn't you use SageMaker Async Endpoints? 

### ISSUE THREAD

**Issue by philschmid** [aws-samples/amazon-scalable-infra-discord-diffusion#1]
Hello, 

First of all pretty amazing example! Super helpful! 
But I am asking myself why you didn't go with SageMaker Async endpoints. 
What you have created with the CW alarms and Step functions + sqs is what SageMaker Async Endpoints offer. 
Meaning the complexity from creating all of the infra could be reduced to: 
API Gateway -> Lambda -> SageMaker Async Endpoint, which also scales to 0 and has a queue etc.

**Comment by ddrmaster1000** [comment]
Amazon Sagemaker Async Endpoints are an ideal for requests with large payload sizes (up to 1GB), long processing times (up to 15 minutes), and near real-time latency requirements which could have been used in this solution. 

For this specific use case, cost optimization was taken into consideration when comparing [Amazon Elastic Container Service ](https://aws.amazon.com/ec2/pricing/on-demand/)(ECS) to [Amazon Sagemaker Async Endpoints](https://aws.amazon.com/sagemaker/pricing/). Currently Amazon SageMaker Async Endpoints provides less instance type options when compared to ECS or Elastic Compute Cloud (EC2). The g4dn.xlarge instance type is currently unavailable for Amazon SageMaker Async Endpoints while it is available for ECS. When comparing to Real-Time Inference there are more instance types available, but the cost is higher when compared to the standard EC2 instances. 

I completely agree that this project could have been simplified by using API Gateway -> Lambda -> SageMaker Async Endpoint. But for this example, the goal was to be able to use smaller instance types that decreased the running cost of the system. Thank you for your insights and for the thoughtful conversation!
