### ISSUE TITLE
How to deploy a custom diffuser model?

### ISSUE THREAD

**Issue by amrakm** [aws-samples/amazon-scalable-infra-discord-diffusion#2]
Where do you load the stablediffusion model in the code? I couldn't find it any reference to huggingface diffusers library.

I would like to use this project to serve a customised stablediffusion model.

**Comment by ddrmaster1000** [comment]
The inference for this project is located here: https://github.com/aws-samples/amazon-scalable-discord-diffusion
That project uses code from the nataili project which offers models besides Stable Diffusion 1.5. It would require some work from your side to change adjust the program for your use case.

**Comment by amrakm** [comment]
Thank you for your quick response!

Is there any advantage of loading the stablediffusion using `nataili` over huggingface `diffusers` library? Any specific requirement for this implementation in specific?

**Comment by ddrmaster1000** [comment]
Both should perform inference of text to image. It comes down to preferences, but the nataili was chosen as it made pulling images simple and will likely have more future capabilities as that project gets built up.
