### ISSUE TITLE
No ECS Container 

### ISSUE THREAD

**Issue by shagunhexo** [aws-samples/amazon-scalable-infra-discord-diffusion#3]
getting the following error when I tried tor un the program following the commands mentioned in the documentation 

service [hexo-discord-diffusion-prod] was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.

**Comment by undrash** [comment]
> 

It might be that the EC2 instance is not spinning up because your AWS account vCPU limit. Look at the activity logs of your EC2 auto-scaling group.

**Comment by ddrmaster1000** [comment]
I will second what @undrash mentioned, please check the vCPU limit for the G type instance class in the region you want to deploy into. Please add a comment if this did not resolve your issue.
