### ISSUE TITLE
Start from zero doesn't run if `message_count` > 1

### ISSUE THREAD

**Issue by undrash** [aws-samples/amazon-scalable-infra-discord-diffusion#4]
I tested the solution and if there's multiple events coming in simultaneously into the queue the start from zero Lambda returns `False` due to this equality check `int(message_count) == 1`

What is the reasoning behind [the check](https://github.com/aws-samples/amazon-scalable-infra-discord-diffusion/blob/main/modules/scaling_alarm_lambda/files/start_from_zero/start_from_zero.py#L33)? Can it just be changed to `> 0` instead, or is it covering some weird edge case?

**Comment by ddrmaster1000** [comment]
This was covering an edge case of starting the process when there are no instances online. But changing it to >0 will still cover the edge case and cover the case of having multiple messages coming in simultaneously. I'll work on making the update.
